version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install nodejs -y
      - ln -s /usr/bin/nodejs /usr/bin/node
      - apt-get install npm -y
      - npm cache clean -f
      - npm install -g npm
      - npm install -g n
      - n stable
      - npm install -g angular-cli
      - gradle_version=2.6
      - wget -c http://services.gradle.org/distributions/gradle-2.6-all.zip
      - unzip  gradle-2.6-all.zip -d /opt
      - ln -s /opt/gradle-2.6 /opt/gradle
      - printf "export GRADLE_HOME=/opt/gradle\nexport PATH=\$PATH:/opt/gradle/bin\n" > /etc/profile.d/gradle.sh 
      - . /etc/profile.d/gradle.sh
      - gradle -v
      - chmod +x ./gradlew
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      - cd client && ng build --prod
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - index.html
    - scripts/*
    - build/**/*
    - client/dist/**/*
  discard-paths: no

