/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'derekferguson' at '2/4/17 9:30 AM' with Gradle 3.0
 *
 * @author derekferguson, @date 2/4/17 9:30 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
