#!/bin/bash
DB_PASSWORD=`aws ec2 describe-tags --region=us-east-1 --filters "Name=key,Values=dbPassword" --output=text | cut -f5`
/usr/lib/jvm/jre-1.8.0/bin/java -jar /var/www/html/gs-spring-boot-0.1.0.jar > /dev/null 2>&1 &
